### ISSUE TITLE
Improve development workflow support for Portal environments (watch)

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-js-toolkit#175]
Version `2.2.0` introduces a command to generate a `.jar` file that one can deploy into an instance of Liferay Portal.

Following this, we should try to add some helpers similar to those in [liferay-themes-sdk](https://github.com/liferay/liferay-npm-build-tools/issues/164) to allow for easy `deploy` and maybe even `watch`

**Comment by matuzalemsteles** [comment]
hey @jbalsas @izaera, I was a few days ago trying to work on a watch for the Portal to help the Forms team be more productive with the migration... I just want to leave some details I had when trying to do and work along with `liferay-npm-bundler`.

### webpack
I tried first to go with the webpack, since it already has a proxy system to serve the files would make it easy to walk with it, but it was difficult to set a configuration so that the webpack output AMD files, it is very locked to your module resolution settings, it becomes very impractical and would have a lot of work to set up...

### babel-cli
Babel-cli is very simple but it provides a watch system for your files, it monitors the files that are changed and transforms only those changed but does not provide any escape port so we can create something with it, maybe a plugin to run the `liferay-npm-bundler` underneath the cloths (but I did not try anything), I created a small babel-cli to monitor the files that are changed and transform them, for each changed file I tried to run `liferay-npm-bundler` but it does not provide any form of power transforms only one file, it changes all the files that exist in the folder and duplicates the `define` of AMD in the files...

I did not get to go deep with the presets and plugins that is provided by `liferay-npm-build-tools` to add to babel-cli, but I also do not know if it solves all use cases...

To serve the files I got to use the browser-sync and created a quick setup, it worked very fast when changing only one file the first time, but in the others `liferay-npm-bundler` ends up modifying all the files and duplicating the `define`...

### browser-sync
Browser-sync offers many workarounds to serve files, with some 150 lines I managed to make it monitor the `src` files and serve the `classes` files as a proxy for Liferay. But the solution you have to run with it was to always run babel's `build` and `liferay-npm-bundler` each time a file is modified. It's faster than giving a `gw deploy` but it can be faster...

Maybe if you could pass it to the `liferay-npm-bundler` CLI the file input and it use the settings `.npmbundlerrc` to modify, would greatly help create such things and have integrations with other tools.

### Plugin for the liferay-npm-bundler
I even tried to create a plugin for `liferay-npm-bundler` but the plugins do not have as much power over the CLI... I did not follow with that idea. But it would be super interesting to have more power for the plugins...

### Some points
I did not delve into the subject, but it would be interesting if the CLI had more options so people could easily try to integrate with their stacks. But it would also be interesting to have some plugin to serve the proxy files inside `liferay-npm-bundler`.

**Comment by jbalsas** [comment]
Hey @matuzalemsteles, thanks a lot for that detailed analysis!! 

Before diving into it... did you guys try to use the existing `gradlew watch` task in Portal? That should be enough to improve developer experience on that side...

**Comment by izaera** [comment]
In addition, @matuzalemsteles, I'm not sure if a plugin for the bundler would do the work. The problem is that the bundler is just an step in the build process but doesn't know anything about the rest of the steps, therefore it seems impossible to implement the watch in the bundler alone.

**Comment by matuzalemsteles** [comment]
hey @jbalsas, Yes people tried to use, but are not very happy with it yet... 🙂

@izaera yes of course I think bundler can become more flexible in terms of configuration by CLI and maybe an API via Node... this would give more possibilities to do something like this. Currently it is quite complete using `.npmbundlerrc`.

**Comment by izaera** [comment]
This depends on https://github.com/liferay/liferay-npm-build-tools/issues/179

**Comment by jbalsas** [comment]
Doing some autumn cleaning as we move this project to https://github.com/liferay/liferay-frontend-projects#js-toolkit

We'll be curating these and creating new ones mostly from scratch to have a better sense of where we want to go.
