### ISSUE TITLE
Working with ng cli and npm bundler (approach could be extended to work with create-react-app and vue-cli).

### ISSUE THREAD

**Issue by travisrcory** [liferay/liferay-js-toolkit#283]
# Working with ng cli and npm bundler

Currently it is difficult to create a canonical angular app with the Liferay build tools. One proposed idea is to make use of the angular.json configuration and [fileReplacements](https://angular.io/guide/build#configure-target-specific-file-replacements). The idea would be to have something like:

`package.json`:

```
"deploy": "ng build --prod && liferay-npm-bundler"
```

As you can see in the link listed above, you are able to replace file imports based on environments. For examples of this you can take a look at [liferay-angular-playground](https://github.com/travisrcory/liferay-angular-playground/tree/master/modules/my-project). 

By default the developer would make use of relative URL's for everything they are developing, so that their dev experience would be similar to any other angular app. The developer would also have a file called something like `environment.liferay.ts` that would contain something like:

```
const contextWebPath: string = '/o/my-project';

export const environment = {
  path: {
    app: `${contextWebPath}`,
    components: `${contextWebPath}`
  }
};
```

This file could also be built out to substitute the absolute URL for style URLs, for individual components, etc. While this is a file that needs to be managed, the hope is that they could set it up once (or modify / add as needed) and then start development as expected. Then when ready to deploy to liferay they can run `npm run deploy` to build the app and then run the bundler process. The angular.json file would need to be set up to output the built component to the correct directory so that it can be compiled for use in Liferay.

### This approach could potentially be used to test and come up with a possible approach to working with create-react-app and vue-cli.

The idea to test is: "Are we able to add steps to advise on how to use commonly used tools for Angular, React, Vue development tools with our tooling (with obvious gotchas)"

**Comment by travisrcory** [comment]
@izaera, @jbalsas, @rozamirandar, @alexandervalencia just adding this here to get the conversation started, feel free to add anything or help provide feedback. Thanks for all you guys do! I'll be away for a couple weeks so you won't hear much from me.

**Comment by yuchi** [comment]
Quick note: with Create React App we usually simply change the `PUBLIC_URL` env variable to `/o/xxxxxxx` when building for the module, and then read the automatically generated _asset-manifest.json_ file to identify main assets to include in the page.

**Comment by yuchi** [comment]
We == SMC

**Comment by mwilliams2014** [comment]
FYI, I've used this approach in our sample guestbook app for docs with single Vue components: https://github.com/mwilliams2014/liferay-docs/tree/LRDOCS-6298-deploying-a-vue-widget/developer/appdev/code/vue-guestbook/after/vue-guestbook-migrated

**Comment by izaera** [comment]
Hey @travisrcory, I'm revisiting issues and it's not clear to me what is the intention of this one :thinking: .

This was created before the `adapt` feature that lets you deploy projects created with create-react-app, ng-cli and vue-cli to Liferay DXP so it may not be needed any more. However I see that your approach was not to deploy pure framework projects, but to tune the build for Angular projects so that you can use `ng` to test, for example.

Is this feature still valid? If so, can we rephrase the title of the issue so that it is clear what we are trying to achieve?

As I said, looking at the playground you provided, it looks like a tweak of the minimalist build we provide with the generator, but I'm not sure if it would make sense to merge it into the generator as there may be lots of ways to achieve the same so I'm inclined to thinking that it should be left to the "developer's side" instead of putting it into the JS Toolkit :thinking: .

There's also another issue tackled by the playground, which is the use of relative URLs in Angular projects. I think it would be better if we can split this issue in its atomic constituent parts and create new issues for each one.

What do you think?
