### ISSUE TITLE
Add support for static resource loaders (treat CSS, SVG, JSON, etc. as JS modules that may be imported)

### ISSUE THREAD

**Issue by rozamirandar** [liferay/liferay-js-toolkit#303]
It would be nice to have a way of dynamically loading CSS code as it's done with Javascript AMD Modules.

@izaera @jbalsas

**Comment by sohui** [comment]
It would be great to have this feature.

**Comment by sohui** [comment]
`import styles from './index.css';
import { formatMessage } from 'umi-plugin-locale';

export default function() {
  return (
    <div className={styles.normal}>
      <div className={styles.welcome} />
      <ul className={styles.list}>
        <li>To get started, edit <code>src/pages/index.js</code> and save to reload.</li>
        <li>
          <a href="https://umijs.org/guide/getting-started.html">
            {formatMessage({ id: 'index.start' })}
          </a>
        </li>
      </ul>
    </div>
  );
}
`
when import css, it raised errors.

ERROR in ../src/pages/index.css 2:0
Module parse failed: Unexpected token (2:0)
You may need an appropriate loader to handle this file type.

**Comment by izaera** [comment]
@rozamirandar In addition to CSS resources, webpack also supports static media (like svg, jpg, and the like).

The general contract seems to be:

1. `import css` adds the CSS to the CSS bundle (in our case it should add a `com.liferay.portlet.header-portlet-css` property to the portlet, probably)
2. `import svg|jpg|...` returns a string with the URL of the resource (in our case we should look at the web context path to know how to get it, but I'm not sure what to do with the `/o` prefix: should we hard code it? make it configurable just in case someone changes it? ...?)

**Comment by izaera** [comment]
Also, we need to take into account that the portal may have a proxy, CDN, or a custom webapp root configured. I don't know if that needs anything specific whether in the server or the build side... :thinking:

**Comment by jbalsas** [comment]
I think we'll need different CSS loaders... if someone's doing some type of CSS-in-JS, they might just want a representation of the CSS stylesheet (maybe a `CSSStyleSheet`?). Someone else might want to just throw that into a `style` tag. 

Similarly for svgs, I've seen svg-loaders to actually expose the different symbols inside the svg.

Ideallly, we would want some type of glob-to-loader mechanism.

**Comment by izaera** [comment]
:thinking: Making the assumption that this kind of imports only appear in the project's code (as opposed to third party dependencies), the easiest ways to tackle this is -probably- to use babel plugins during the bundler's build phase to transform these `require`s into something meaningful.

I say `require`s because the bundler expects CommonJS modules (not ES6) and because we would be taking advantage of the babel phase of the bundler, we should expect:

```javascript
import myCss from 'perico.css';
```
to have already been converted to:

```javascript
var myCss = require('perico.css');
```

Of course, we should remove `perico.css` from the list of deps in the `Liferay.Loader.define()` call and transform that `require()` into some other thing: perhaps an inline URL composition, or an insertion of an <script> node, ...

That could be much more easier (emit code and do everything at runtime) than trying to tune the artifacts in separate places during build time.

**Comment by jbalsas** [comment]
It should be simpler to just treat those as module dependencies just like the rest. 

The only difference would be that, inside the `amd-loader`, a `.css` file could be handled by a `css-loader` that would take care of resolving the dependency with whatever they deem necessary, providing whatever implementation they want and satisfying both the loader dependency graph and the consumer contract.

**Comment by yuchi** [comment]
Just my obligatory out-of-context comment. When designing the API for application code you can pretty make any choice you want. But in the wild I saw libraries actually *expecting* consumers to be on Webpack-like loaders…

**Comment by izaera** [comment]
Webpack's model works at build time, not runtime, so I assume the more we stick to that, the less problems we will have. That's why I think it's better to do it with a babel plugin.

Also that has the benefit that we don't need to do anything in the Portal or the loader, which has a slower lifecycle when it comes to support it.

Doing the resolution during runtime has the benefit that you can later change the stategy, but that implies configuration which makes the solution more complex. And I doubt (though I'm not 100% sure) that anybody may need to override developer's decision. Also, it's not clear if it would be a good idea at all. It's probably better to just rebuild the project if you want to change the strategy (as webpack does).

Imagine, for example, doing an `import 'styles.css'`:

1. If you resolve it during build time it just adds a property to the portlet and everything is then from then handled in a standard efficient way
2. If you resolve it at runtime, the loader needs to have a custom piece to:
      a. Decide where to fetch the file from
      b. Decide what to do with it: whether it is injecting a tag to the DOM or parse it as a JS object

For me, it's clear that 1 is far superior in terms of simplicity, efficiency, and maintenance in the future :thinking:

**Comment by sohui** [comment]
@izaera So is it a good idea to support CSS Module in JS Module when generate JS portlet?

**Comment by izaera** [comment]
@sohui I would say yes :man_shrugging: That's why we have created this issue... :-)

**Comment by izaera** [comment]
Finally merged :tada: .

I have left a showcase on how it is supposed to be used here :point_right: https://github.com/izaera/liferay-js-toolkit-showcase/tree/loaders

I will also document how to use it in the wiki.
