### ISSUE TITLE
Angular portlet performance

### ISSUE THREAD

**Issue by ericdariel** [liferay/liferay-js-toolkit#344]
Hello,

We have made a very simple Angular 6 portlet but first time, we have to wait about 5 seconds to see it.
The second time we have to wait 3 seconds. 
Do you know how we can do to speed up our portlet?

Maybe Angular 8, can be more faster? Do you plan to upgrade to angular 8 next month?
Do you know how we can speed up our portlet may be if we add anything in our theme?

Another solution would be to add Angular lib in the JS extender? 
Do you think it is possible to have an JS extender for Angular and an other for React... ??? 

We want to create many angular portlets, it will be great if we can load angular libs only one time for all of our portlets.

Anyone can help us?

Eric.

**Comment by izaera** [comment]
> Do you know how we can do to speed up our portlet?
> Maybe Angular 8, can be more faster?
> Do you know how we can speed up our portlet may be if we add anything in our theme?

Not really. Without knowing what the portlet is doing the slowness can be due to anything (the server, Angular, the project setup, ...)

If the portlet is just the default project as generated by our Yeoman generator, what do you mean by "the second time"? Do you mean after refreshing the page? After navigating and coming back to the page again? Other?

IMO, the first thing we need to do to diagnose the slowness is to determine if it is a server or a browser problem.


> Do you plan to upgrade to angular 8 next month?

In principle, not. But you can try to upgrade your project to Angular 8. If nothing radically new has been added to Angular 8 it should work.


> Another solution would be to add Angular lib in the JS extender?
> Do you think it is possible to have an JS extender for Angular and an other for React... ???
> We want to create many angular portlets, it will be great if we can load angular libs only one time for all of our portlets.

The JS extender is not intended for that. If you want to share packages among several portlets use the `imports` feature of the bundler. See [this repo](https://github.com/izaera/liferay-js-toolkit-showcase/) for a detailed example on how to share packages. It is based on React, but the setup should be similar for Angular.

**Comment by izaera** [comment]
I'm closing this because it has been answered. Feel free to reopen it if further questions arise.

**Comment by ericdariel** [comment]
OK thanks.
If I test with the default generated portlet, it is the same. The first time it takes 3 seconds with a good connection and 5 seconds with my phone.
The second time I go on the same page, it takes 2 seconds (3 with my phone).
I think it is the loading of the angular libs.
If I find time, I will try to upgrade with angular 8.

**Comment by izaera** [comment]
@ericdariel What version of Portal are you using? 

We had to make some changes to the way module resolution works (https://issues.liferay.com/browse/LPS-83949) to resolve everything in the server because before that we had to download a huge resource with all module definitions (served by `http://localhost:8080/o/js_loader_modules`). 

Such resource may be minified and compressed to alleviate the problem, but it is still big enough to be noticed.

**Comment by izaera** [comment]
If that is the case, changing Angular version won't help because the problem would be not with Angular or any specific framework, but with the number of JS modules you have deployed in your system no matter if they are Angular, React, or plain JavaScript libraries :-(.

**Comment by izaera** [comment]
In 7.1 there's an option in `Control Panel > System Settings > Frontend Infrastructure > Use 4.x loader` (or something like that, I'm talking off the top of my head) that activates the server side resolution algorithm and should make things faster.

If you don't see that option then, most likely, you don't have [LPS-83949](https://issues.liferay.com/browse/LPS-83949) applied.

**Comment by rmandovnz** [comment]
> In 7.1 there's an option in `Control Panel > System Settings > Frontend Infrastructure > Use 4.x loader` (or something like that, I'm talking off the top of my head) that activates the server side resolution algorithm and should make things faster.
> 
> If you don't see that option then, most likely, you don't have [LPS-83949](https://issues.liferay.com/browse/LPS-83949) applied.

Wowww, this was amazing. thank you, if anyone know more about the optimization steps/guide for angular/dxp will be really appreciate.

I share the diff between before/after of the recommendation of @izaera mention on the actual project im working on.

![dxpOptimization](https://user-images.githubusercontent.com/1782472/59473887-066af200-8e0a-11e9-937f-d3179f8dd4ec.PNG)

**Comment by ericdariel** [comment]
Thank you izaera, I see this option after the installation of the latest 7.1 fix pack.
It seems to be faster and especially after the first load. 

But warning, I found a problem if I create a new angular portlet from scratch with the yo liferay-js.
My portlet doesn't render the first time. I have to deactivate the option "Use 4.x loader" to see it. After that, I can see my portlet and reactivate the option.
I have reproduce the problem 2 times yesterday, it is only the first first time when I put a new generated portlet on a page.

I see another problem with the angular portlet, the configuration seems to not work. I can choose my favorite beverage (beer) in the configuration panel but after I can't see my choice in the portlet.
I use the default generated angular portlet.

Thank you for your precious time, 
Éric.
