### ISSUE TITLE
Custom filename for generated jar

### ISSUE THREAD

**Issue by reinrl** [liferay/liferay-js-toolkit#345]
As I am working through the development/deployment lifecycle for a new portal project, it seems desirable to control the filename of the generated jar (specifically to remove the last hyphen, as well as the version number, from the generate filename when using the "create-jar" option in .npmbundlerrc), similar to how the output directory is both defaulted and configurable.

(pull request coming shortly, as I believe that I had worked out how to do this locally - although I realize that some additional documentation changes would likely be required, and am entirely open to having glossed over an existing way to accomplish this same bit).

**Comment by izaera** [comment]
Thanks for the contribution @reinrl :slightly_smiling_face: .

Unfortunately, contributing documentation seems a pretty difficult task in GitHub :disappointed: . We document everything in the [project's wiki](https://github.com/liferay/liferay-js-toolkit/wiki) but for some strange reason GitHub doesn't allow forks or pull requests for the wikis (though they have an associated git repo :woman_shrugging: ). 

On the other hand, I don't want to open edition of the wiki to everybody because not so much people contribute and I feel it may be more a problem than an advantage.

So don't worry, I'll take care of the documentation of this issue. 

In the future, if you want to send some documentation we can find a way to contribute it. Given that it is based on git, there are workflows based on patches, for example, that can be used for this (I guess/hope).
