### ISSUE TITLE
"browser" modules' require() calls fail when they are located in a different folder than the replaced module

### ISSUE THREAD

**Issue by mfreeman-xtivia** [liferay/liferay-js-toolkit#363]
Buidling a portlet using package "superagent" for http communications. This has worked successfully using webpack and other bundlers. I have tried this with both superagent  5.0.8 and 5.1.0

'npm build' runs fine with no errors and deployment is fine as well. However upon loading the portlet I am receiving the following errors from the Liferay loader:

```
The following problems where detected while resolving modules:
    · Missing dependency 'jetray-amd$superagent@5.1.0/lib/node/request-base' of 'jetray-amd$superagent@5.1.0/lib/node/index'
    · Missing dependency 'jetray-amd$superagent@5.1.0/lib/node/is-object' of 'jetray-amd$superagent@5.1.0/lib/node/index'
    · Missing dependency 'jetray-amd$superagent@5.1.0/lib/node/response-base' of 'jetray-amd$superagent@5.1.0/lib/node/index'
    · Missing dependency 'jetray-amd$superagent@5.1.0/lib/node/agent-base' of 'jetray-amd$superagent@5.1.0/lib/node/index'"
```

From what i can see by staring at the results it appears that the bundler may be having some issues with "double dots" in the require statements, e.g., require '.../foo". 

As an example of the problem, the node/lib/index.js file is coded like this in the original code ...

`var RequestBase = require('../request-base');
`

but in the ready-to-be-jarred code in the 'build' folder after transpilation has run and the npm bundler plugins have done their work the statement looks like this now...

`var RequestBase = require('./request-base');`

which then causes an incorrect amd define statement to be generated....

Liferay.Loader.define("jetray-amd$superagent@5.1.0/lib/node/index", ['module', 'exports', 'require', 'jetray-amd$component-emitter', 'jetray-amd$fast-safe-stringify', **'./request-base'**, './is-object', './response-base', './agent-base'], function (module, exports, require) {

**Comment by izaera** [comment]
The real problem is not with `..` but with the semantics of the `browser` section of `package.json`.

The `package.json` of `superagent` contains the following:

```
  "browser": {
    "./src/node/index.js": "./src/client.js",
    "./lib/node/index.js": "./lib/client.js",
    "./test/support/server.js": "./test/support/blank.js"
  },
```

which, to any bundler, means `replace './lib/node/index.js' with './lib/client.js'` which is what the `liferay-npm-bundler-plugin-replace-browser-modules` exactly does by copying `./lib/client.js` on top of `./lib/node/index.js` before processing the package.

Unfortunately the strategy `liferay-npm-bundler-plugin-replace-browser-modules` follows seems to be incorrect, because `./lib/client.js` expects its `require()`s to be resolved relative to its dir, and not the replaced file's directory.

And that's what makes it fail.

**Comment by izaera** [comment]
https://issues.liferay.com/browse/IFI-1070

**Comment by izaera** [comment]
https://issues.liferay.com/browse/IFI-1070
