### ISSUE TITLE
Custom Bundle-SymbolicName

### ISSUE THREAD

**Issue by wsyski** [liferay/liferay-js-toolkit#369]
This is only a question. At the moment the Bundle-SymbolicName and the jar file created is taken from the package.name. This results in a jar with a name angular-widget-1.0.0.jar. Would be possible to add a package so the resulting jar file name and Bundle-SymbolicName could include a package path: ex. com.liferay.npm.sample? I have tried:
"customManifestHeaders": {
            "Bundle-SymbolicName": "com.liferay.npm.sample.angular-widget"
}
but it has not worked.

**Comment by izaera** [comment]
That will never work, because even if you set it, it is also by the tool [here](https://github.com/liferay/liferay-js-toolkit/blob/master/packages/liferay-npm-bundler/src/jar/index.js#L112), so you will end up with two headers.

However, you can tweak the JAR's filename as seen [here](https://github.com/liferay/liferay-js-toolkit/wiki/.npmbundlerrc-file-reference#create-jaroutput-filename). But of course, that wouldn't help with the bundle's symbolic name.

I would say that there's no reason why the bundle and the JS package name *must* be the same, other than mental sanity :-D.

Said that, nobody has ever tried to do that (because the tools doesn't allow it, of course) so it may be very possible that if we try it, we find something that prevents it from working. But I wouldn't be against it if you really need it...

What do you think @jbalsas? Are you aware of any reason why we are forcing everybody to have a `Bundle-SymbolicName` equal to the package.json `name`?

Shall we try to support different names?

**Comment by jbalsas** [comment]
Hey @izaera, I assume we just tried to simplify things. Too many configuration options and developers start drowning in a sea of documentation and possible configurations...

That being said, I don't see why we shouldn't support this. However, if you want both the `jar` and the `symbolic-name` to have the namespace... why not simply changing the `name` in the `package.json`?

**Comment by wsyski** [comment]
Yes I agree with your argumentation. Thanks.
