### ISSUE TITLE
React app doesn't display errors on console

### ISSUE THREAD

**Issue by hsandrade** [liferay/liferay-js-toolkit#391]
Hi,

Comming from a tradicitional react app, we can import components that are inside a folder without specify the 'index' file, so if we have a folder structure like /src/routes/index.js it can be imported like **import Routes from './src/routes'** for example, but if do this, the application doesn't work after deploy on Liferay, and no error is thrown on browser console or Liferay logs! Only works if we explicity inform de whole path like **import Routes from './src/routes/index'**

The major problem was that no error as thrown and I have wasted a lot of time to understand that was related to the path. I'm worried because we're to use this tool to build react widget and it's important to trace the errors. 

There is a way to display any type of error in a widget created with Liferay JS Tools, like in the above situation?

I've Created the app using the instructions here: https://portal.liferay.dev/docs/7-2/appdev/-/knowledge_base/a/developing-a-react-application#developing-a-react-application

Environment:
- Linux Ubuntu 18.04
- Liferay DXP 7.2 Patch 1
- Google Chrome 76.0

Thanks

**Comment by izaera** [comment]
> There is a way to display any type of error in a widget created with Liferay JS Tools, like in the above situation?

You can follow the steps explained in the [wiki](https://github.com/liferay/liferay-js-toolkit/wiki/How-to-troubleshoot-your-setups). Especially activating `Explain module resolutions` should help.

We will be enhancing the support for diagnostics in the future, though, because it's a bit limited and complicate to use now, so I'll leave this open.

**Comment by rdai10** [comment]
Would it make sense to turn logging on by default?

**Comment by izaera** [comment]
@rdai10 not really, because:

1. you don't want those logs to appear in production
2. the logs are so detailed now that they flood your console so there's no point in activating them unless you already know that you will be extracting something out of them

That's why I said we should first make it easier to filter the detail level of those messages and then we can think about which level to activate by default :-).

**Comment by izaera** [comment]
This will be addressed in a different project. See https://github.com/liferay/liferay-amd-loader/issues/212
