### ISSUE TITLE
session vars

### ISSUE THREAD

**Issue by pedrodelg** [liferay/liferay-js-toolkit#404]
Hi!

I'm developing a react portlet with yeoman in liferay 7.2, I need to send some data in session vars in order to recieve that data in another page, but I don't now how to send session var with javascript in a yeoman portlet. Could you tell me how to send that kind of data in session?. thank you very much.

**Comment by izaera** [comment]
The session is inherently a server side thing, so there's no way you can set anything in session from JavaScript.

That said, I suppose you can create a server API to set things in session and call it from the client side. But I doubt that's what you really want to do...

What you need is to pass some data from one page to other page and you should probably structure your application in such a way that that data is passed from the client to the server so that the server stores it and can use it in the other page...

Alternatively, you can store that data in the client side (by using localStorage or cookies) but given that the space is very limited and the availability could be compromised, doesn't sound like a good option, unless you have some good reasons to do it that way.

**Comment by jbalsas** [comment]
You should have `Liferay.Store` methods available same as any other `Liferay` already existing JavaScript APIs

**Comment by wincent** [comment]
> You should have `Liferay.Store` methods available same as any other `Liferay` already existing JavaScript APIs

(Just in case it's not clear from the name or well-documented what those actually do, they can be used to write data to the server-side session storage, and read it back from it.)

**Comment by jbalsas** [comment]
> (Just in case it's not clear from the name or well-documented what those actually do, they can be used to write data to the server-side session storage, and read it back from it.)

And assuming you're in `<7.3.x` where it will be renamed as `Liferay.Session` 😂

**Comment by pedrodelg** [comment]
could you tell me how to set and get parameters with Liferay.Session? I'm looking for information about it but I don't find!

**Comment by izaera** [comment]
The syntax is very straightforward:

```javascript
  Liferay.Util.Session.set('key', 'value');
  Liferay.Util.Session.get('key');
```

**Comment by pedrodelg** [comment]
![459d38e4-3b1d-4f9a-9a22-1fe222e29c1a](https://user-images.githubusercontent.com/18012032/65163720-0f6af100-da01-11e9-8478-89c1a05fa0ff.jpg)
I get this error
