### ISSUE TITLE
Build:liferay fails if create-react-app's index.js does not import a CSS file

### ISSUE THREAD

**Issue by reinrl** [liferay/liferay-js-toolkit#406]
As a starting point, I created a project using create-react-app and then adapted it to be bundled as a Liferay portlet. Initially, everything built fine.

My desired end result was to include styling when running the app in standalone mode ("npm run start"), but then not bundle any CSS with the project when building and deploying to Liferay - instead, letting the deployed theme handle all aspects of styling. To accomplish this, I removed the import for the local stylesheet (_import ".index.css";_ on index.js), and instead included a project-local stylesheet on /public/index.html.

As soon as I made this change, and ran the build:liferay script, I received the following error:

```
//... previous step is copying all dependent packages, just copied the last one for context

Copying package 'workbox-window@4.3.1'...
(node:10416) ExperimentalWarning: The fs.promises API is experimental
Copied 1 packages
Applying rules to package '/'...
Applied rules to 1 packages
Transforming package '/'...
Babelifying 0 files in package '/'...


Error: ENOENT: no such file or directory, scandir 'build.liferay\jar\react-app\static\css'
    at Object.fs.readdirSync (fs.js:875:3)
    at Object.exports.default [as run] (C:\dev\prototyping\myproject\node_modules\liferay-npm-bundler-plugin-create-react-app\lib\index.js:22:30)
    at C:\dev\prototyping\myproject\node_modules\liferay-npm-bundler\lib\steps\util.js:151:10
    at Array.forEach (<anonymous>)
    at runPlugins (C:\dev\prototyping\myproject\node_modules\liferay-npm-bundler\lib\steps\util.js:137:10)
    at C:\dev\prototyping\myproject\node_modules\liferay-npm-bundler\lib\steps\transform.js:142:37
    at new Promise (<anonymous>)
    at runBundlerPlugins (C:\dev\prototyping\myproject\node_modules\liferay-npm-bundler\lib\steps\transform.js:140:9)
    at C:\dev\prototyping\myproject\node_modules\liferay-npm-bundler\lib\steps\transform.js:120:10


Error: Node modules binary 'liferay-npm-bundler' finished with status 1
    at runNodeModulesBin (C:\dev\prototyping\myproject\node_modules\liferay-npm-build-support\lib\util.js:117:9)
    at C:\dev\prototyping\myproject\node_modules\liferay-npm-build-support\lib\scripts\build\create-react-app.js:108:38
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myproject@1.0.0 build:liferay: `lnbs-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myproject@1.0.0 build:liferay script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\me\AppData\Roaming\npm-cache\_logs\2019-09-10T15_27_53_252Z-debug.log
```

Adding the index.css import back in immediately removed the error, and allowed the jar to be successfully built. Am I correct in interpreting this as an assumption on the bundler's part that a CSS file import must exist (even if the stylesheet itself is empty)? If so, should it?

**Comment by izaera** [comment]
OK, looking at https://github.com/liferay/liferay-js-toolkit/blob/master/packages/liferay-npm-bundler-plugin-create-react-app/src/index.js#L26 it's clear that we are assuming that the `static/css dir` exists.

I would say that we can fix that, because it's clearly a bug.

However, the intent of the create-react-app integration was to mimic the exact behavior you get when bundling with webpack in Liferay. So, I understand what you want to do, but I would advice not to divert too much from what webpack does because it can lead to problems in the future.

Tweaking the CSS is probably OK and won't ever be a problem, but keep in mind that tweaking both builds (the one from webpack vs the one from the bundler) making them divert too much doesn't sound like a good idea :sweat_smile: .

**Comment by reinrl** [comment]
@izaera Understood (although it makes standalone app development easier on our end). Said differently: "I don't want to have any CSS in my project because I want it to use styling declarations coming from the theme once it is deployed as a portlet to a Liferay portal instance. Should an expectation exist for at least an empty CSS file (and then have it bootstrapped to the portlet when bundled), or does supporting the use case of no CSS files in your portlet project seem reasonable?"

**Comment by izaera** [comment]
@reinrl Yes, as I said that expectation looks reasonable :-). 

The main things we are assuming have to do with bootstrapping the application, because CRA uses a html page which we don't parse so, anything you place there won't be honored when deploying to Liferay. That means that you can put webpack specific code and it won't appear in Liferay (like you do with your CSS).

Specifically, we bootstrap from index.js and assume that it will have a React.render() statement with a document.getElementById() call -> https://github.com/liferay/liferay-js-toolkit/blob/develop/packages/liferay-npm-build-support/src/scripts/build/create-react-app.js#L233

Other than that we also inject all existing CSSs in the portlet header -> https://github.com/liferay/liferay-js-toolkit/blob/develop/packages/liferay-npm-bundler-plugin-create-react-app/src/index.js#L25

We can change that last bit so that if no css files are found we don't do anything and it will probably work forever.

It could be the case that in the future we decide to parse the HTML to try to mimic it in Liferay, though I think it won't ever happen because it looks like it will bring a bunch of problems and casuistic which would be very difficult to handle IMO. 

Nevertheless, say that we decide to parse the HTML, it would break your setup, but you would detect it immediately after a deploy and we could offer a flag to tune the HTML parsing, so it doesn't look like a horrible assumption even in the case where we break it in the future.
