### ISSUE TITLE
Angular CLI Integration?

### ISSUE THREAD

**Issue by mfreeman-xtivia** [liferay/liferay-js-toolkit#445]
Can the existing Liferay JS toolkits be used/integrated with the Angular 8 CLI?

Put another way to tap into the configuration capability and the JS Extender etc do we have to go the route of the yeoman generator and the external webpack based builds? Or can we somehow use these capabilities in the context of using Angular CLI as the main build tool?

**Comment by izaera** [comment]
Hi @mfreeman-xtivia, what you are asking is implemented in issue #429, which will be released soon.

However, be warned that "adapting" (as we call it) an Angular CLI application has its drawbacks, the main being that you bundle the whole Angular and its dependencies inside the portlet, so there's no way to reuse them if you want to share it with other portlets, for example.

This is because what we do is simply running the webpack build and embedding webpack's output bundle inside a portlet wrapper.

Also, because you are "adapting" and there are mismatches between Angular's model and Liferay's one you may lose several Liferay specific features (like for instance: support for System Settings or Portlet Instance Configuration).
