### ISSUE TITLE
Analyse what can/can't be done for the Integration with vue-cli

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-js-toolkit#451]

**Comment by izaera** [comment]
I already have a working version in my local disk. It is pretty much the same as the Angular CLI integration, but it needs rewriting the static assets URLs as in React.

I suspect that the rewrite may be also necessary in Angular but we haven't detected it yet. I make this assumption because from the Vue CLI documentation:

> Internally, we use file-loader to determine the final file location with version hashes and 
> correct public base paths, and use url-loader to conditionally inline assets that are smaller 
> than 4kb, reducing the amount of HTTP requests

so it makes sense that Angular may be doing that too. Right now, when you adapt the initial demo, the only image it shows is bundled as a `data:` URL, but I suppose that if it was bigger it would be served statically as it doesn't make sense to bundle lots of MB in `data:` URLs.

Nevertheless, given that the three frameworks need the same steps, I think we will refactor them and create a single codebase. In the end, webpack bundling leads to very similar results so I don't expect that the 3 frameworks will diverge in the future unless one of them stops using webpack. And even so it's difficult to think how the output could change so much as to make us split the adaptations again.
