### ISSUE TITLE
CRA issue with new js syntax.

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/liferay-js-toolkit#454]
I am having issues adapting a CRA component that uses react fragments and also complains about rest/spread operators. Do I need to configure something in particular for this? I didnt have this issue previously, but now its coming up.

**Comment by izaera** [comment]
@bryceosterhaus Can you elaborate a bit more? Who complains?

**Comment by izaera** [comment]
This seems to be caused by our `create-react-app` build using Babel 6 which doesn't support React's fragment (`</>`) syntax.

Because we are going to refactor the whole `create-react-app` build, I will merge an experimental fix and release a canary version so that you can use it until I make the final release, in which we won't be using Babel at all.
