### ISSUE TITLE
Angular portlet performance problem

### ISSUE THREAD

**Issue by wsyski** [liferay/liferay-js-toolkit#457]
I have developed a fairly large angular portlet using several angular frameworks in Liferay 7.2. Everything builds and executes fine.  Unfortunately I experience a serious performance problem when loading the portlet. It takes about 1.5 seconds to load all the modules required by the portlet. It takes about 15 combo requests to fetch all the modules. My users refuse to accept this. Is there any way to make things faster (caching, pre-compiling etc.)?

**Comment by izaera** [comment]
Mmm, not that I can think of... 

The problem is that the loader has a [limit on URL length](https://github.com/liferay/liferay-amd-loader/blob/master/src/loader/config.js#L32) that by default is set to `2000` so that the combo request don't exceed proxy and/or server capabilities.

You could try to override that so that a single combo request is made, but that would create a huge URL that may lead to problems and it is also unsupported so the setup could break in the future.

The only thing I can think of right now is to resort to webpack to create opaque modules that may be loaded from Liferay's AMD loader but without its internal structure being handled by the Loader too.

I'm thinking, for instance, in making Angular available through the AMD loader as a module (say `my-angular-provider@1.0.0/angular`) but pack it as a webpack bundle instead as a full npm-bundler project.

We use that approach for [adaptations](https://github.com/liferay/liferay-js-toolkit/wiki/How-to-adapt-most-popular-frameworks-projects) and it works quite well.

I can offer some guidance if you decide to go that way...

**Comment by wsyski** [comment]
I was also thinking about building a kind of angular runtime with webpack (ex. using webpack.DllPlugin as in https://github.com/xtivia/jetray-runtime-angular, but I did not know how to integrate this with liferay npm bundler. Was it the approach you are suggesting? I would welcome your guidance. Do you have a working example? Thanks in advance.
