### ISSUE TITLE
Disable source maps creation

### ISSUE THREAD

**Issue by jamescoq** [liferay/liferay-js-toolkit#468]
Hi, 
would it be possible to turn of creation of source maps in .npmbundlerrc ?

**Comment by izaera** [comment]
You can provide options for babel configuration in the .npmbundlerrc file so that [this if](https://github.com/liferay/liferay-js-toolkit/blob/v2.16.2/packages/liferay-npm-bundler/src/steps/transform.js#L138) does not kick in and source maps are not generated.

All you need to do is to mimick the [default preset's configuration for babel](https://github.com/liferay/liferay-js-toolkit/blob/v2.16.2/packages/liferay-npm-bundler-preset-standard/config.json#L12) setting source maps to `false`.

However, why do you want to disable maps? Is it a common use case? I'm asking because given that it's somewhat complex to disable the source maps like that, it maybe makes sense to do it easier by adding some higher level option to the .npmbundlerrc file :thinking: .
