### ISSUE TITLE
Using Configuration Data in Adapted Applications?

### ISSUE THREAD

**Issue by mfreeman-xtivia** [liferay/liferay-js-toolkit#476]
Is it possible to use configuration data (either system- or instance- scope) in adapted portlets? i.e. portlets that use a CLI and are then adapted to the Liferay framework using "yo liferay-js:adapt"?

As an example if i use vue-cli to create my portlet its not obvious then how i would have access to any of the configuration data known to the Liferay launcher

**Comment by mwilliams2014** [comment]
Hey @mfreeman-xtivia Adapting an app just gets it in Liferay Portal so you can run it. If you want to take full advantage of all the features (configuration, settings, localization, etc.) you should migrate your app instead: https://portal.liferay.dev/docs/7-2/appdev/-/knowledge_base/a/web-front-ends @jbalsas @izaera please chime in if you recommend something else.

**Comment by mfreeman-xtivia** [comment]
But thats not what i want to do.

I LOVE the adapter feature in that it lets me use the native toolkit CLIs and to be honest i would prefer not to go back to the original, pre-adapter model that converts my CJS based modules to AMD modules etc

The only thing missing from making the adapter support drop dead gorgeous is some way to access the configuration parameters

**Comment by mfreeman-xtivia** [comment]
Upon looking at the generated code it appears that the adapter is wrapping my original function in another function that is passed a variable called _LIFERAY_PARAMS_. So in theory i could use that variable inside my application, with sufficient error protection to check if its null?

Would that work?

**Comment by mwilliams2014** [comment]
I'm not sure. Our documentation advises to use migration to have access to the features you mention. If this is an easier route that is best practice, then we may need to revise our docs. If one of the people I mentioned confirms this, I'll make sure they're updated.

**Comment by mfreeman-xtivia** [comment]
As an experiment i tried just copying/mimic-ing the configuration setup that the OOB generator builds (i.e. features/configuration, etc) but that blows up horribly on the server side. 

When i click the "Configuration" link on the portlet, i get a strange "com.liferay.dynamic.data.mapping.form.renderer.DDMFormRenderingException" error

**Comment by izaera** [comment]
@mfreeman-xtivia using the LIFERAY_PARAMS is going to work, but it's not a public API by any means, so it may break in the future without warning and because we don't support it, we may not fix it.

The rationale behind not supporting those features in adapted portlets is that we don't have control over the frameworks, and we need to do some hack to be able to "jump" from the framework's domain to the portal's. That happens when we bootstrap the portlet and attach it to the DOM: usually the frameworks assume they are in a SPA, but we need to divert from that to attaching it to the containing portlet's <DIV>.

If a framework changes tomorrow, we may not be able to bootstrap it as we do know, and we may need to find other way which, theoretically, could break your solution. Either because we cannot pass the LIFERAY_PARAMS any more or because we need to do stranger things.

Said that, it's very unlikely that this happens, but be warned that using LIFERAY_PARAMS is unsupported.

Regarding the `DDMFormRenderingException` I have no idea of what could be happening. DDM is the system that renders the config form which description is contained in a JSON file inside the JAR. Maybe that file is missing or corrupt...

**Comment by mfreeman-xtivia** [comment]
I hear ya, and FWIW it does work as you, confirmed by experimentation on my side. And the DOMRenderingException turned out to be something stupid on my end.

Thanks for the help

**Comment by mfreeman-xtivia** [comment]
Somewhat related to this, another question occurs:

If I use a toolkit preset (e.g. liferay-npm-bundler-preset-vue-cli) and that preset includes a config.json file with its own copy of the "create-jar" setting, is there any way for me to add on to that "create-jar" setting by writing my own extension, or doing something else?

An example would be where i want to add location to my created JAR but the config.json that the preset provides does not include that feature.......

What i am thinking of is some kind of concept along the lines of what the various CLIs do by giving you outlets where you can attach/tweak elements of their built-in webpack configuration

**Comment by izaera** [comment]
:thinking:  The settings in the presets are merged with the settings in your `.npmbundlerrc` but you cannot chain presets. 

So, if you have `.npmbundlerrc` with a preset you get: merge( preset/config.json, .npmbundlerrc )

[Here](https://github.com/liferay/liferay-js-toolkit/blob/master/packages/liferay-npm-build-tools-common/src/project/index.ts#L348) is the code.

**Comment by izaera** [comment]
In the future we will probably allow `.npmbundlerrc.js` files so that users can do the merge as they like.
