### ISSUE TITLE
Is it possible to load modules without specifying the version when calling Liferay.Loader.require?

### ISSUE THREAD

**Issue by mir333** [liferay/liferay-js-toolkit#497]
Hi 

is it possible to set the name by which the package is being referred to in the loader require statement? I'm especially interested in the version can be somehow omitted in the load statement although the package was registered with a version other than 1.0.0. Something on the grounds of best fit, major version...

**Comment by izaera** [comment]
That's not possible because it wouldn't work. We did something similar in the older versions of the Loader architecture, creating aliases for the highest version number, and it ended up in a big mess, because versions constraints of package.json files were not satisfied and things broke.

Why do you want to load the package without the version number exactly?

**Comment by izaera** [comment]
I changed the subject of the issue to what I think you are asking. Feel free to reword it if it's wrong.

**Comment by mir333** [comment]
Hi 
Thanks for the replay. 

My reason was to keep the admin effort down. My JS and widgets are separate modules and I always have just the one version of the JS loaded at the time so it would be easier from the admin side to have a way how to easily require the JS. Now every change of the JS  requires going through the codebase and adjust the loader code because we need to use versioning. 
We have been using the aliases in the past so I was wondering if there was some replacement config for that. Dropping versioning is not an option so I think it's just the way how it needs to be now.

I think I will work around this by using the global configuration and store the current version there.

**Comment by izaera** [comment]
Are you using Java based projects or 100% Javascript?

If I'm not wrong, there's an internal OSGi header to accomplish that (we use it to maintain backwards compatibility), but you would need to use Java based projects, I think.

**Comment by izaera** [comment]
Also, how do you invoke `Liferay.Loader.require()`? Where? And why can't you use `import`/`require` instead?

**Comment by izaera** [comment]
Forget the OSGi header :-(. It implies that a lot of extra (and unsupported) things need to be done if you want to use it. Sorry.

**Comment by mir333** [comment]
We are using the MVC portlets where the loaders is in the JSP but I am also thinking about moving to the 100% JS. Just needs to spend some time on POC. Should be quite straight forward, the only thing what we need to replace is the friendly URL mapper.

**Comment by izaera** [comment]
But still, I don't see why you need to specify versions in any place :thinking: 

If you are in the server you use `<aui:script require="">` and don't need to specify any version, just use the `NPMResolver` service or the `npmResovledPackageName` JSP variable.

And if you are in a 100% JS portlet you are already inside a JS module, so you just use `require()` and it takes care of the version for you.

Am I missing anything?

**Comment by mir333** [comment]
probably there is a problem on my side as I'm using

<script type="text/javascript">
  Liferay.Loader.require("xxxx@1.0.1/yyyy");
</script>

**Comment by izaera** [comment]
That's a way to do it, but not the good way ;-).

You should use `npmResolvedPackageName` like in [this line](https://github.com/liferay/liferay-portal/blob/453d15139bce90d629fac99b469f538f317365f0/modules/apps/item-selector/item-selector-taglib/src/main/resources/META-INF/resources/repository_entry_browser/page.jsp#L503) if you want to load a JS file inside your module.

Otherwise (in case you want to load an external dependency or an imported module) you must use the [NPMResolver](https://github.com/liferay/liferay-portal/blob/453d15139bce90d629fac99b469f538f317365f0/modules/apps/frontend-js/frontend-js-loader-modules-extender-api/src/main/java/com/liferay/frontend/js/loader/modules/extender/npm/NPMResolver.java) OSGi component, which is associated to your bundle and inspects the `package.json` inside it to resolve module names to its correct version.

For example:

`npmResolver.resolveModuleName('my-external-dep')`

would return:

`my-external-dep@1.0.0`

if your `package.json` had:

```
dependencies: {
  ...
  "my-external-dep": "1.0.0",
  ...
}
```

You get the idea...

**Comment by izaera** [comment]
I'm closing this. Feel free to reopen it if any other doubt arises.
