### ISSUE TITLE
Rename liferay-npm-build-tools-common to liferay-js-toolkit-core

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-js-toolkit#526]
And place all common code there (even the one used by generators)

**Comment by izaera** [comment]
As per [this commentary](https://github.com/liferay/liferay-js-toolkit/pull/563#discussion_r419976387) design a proper API for this package.

**Comment by izaera** [comment]
@wincent What would be better as a public API for `liferay-js-toolkit-core?

Keep in mind that it will have different domains which are independent between them. For example:

1) one domain of utilities to read project configuration (the `Project` class)
2) one domain of utilities to transform files in functional fashion (JS, JSON, text, CSS, etc.)
3) TS types describing external file formats and/or protocols (with Liferay portal, for example)
4) logging utilities
5) millenial/hipster printing to the console
6) ...

Should the API be:

1) consumers always `import from 'liferay-js-toolkit-core'` and its main module exports a complex object that describes the domains and utilities and multiplexes into internal files
2) consumers import from different "logical" paths that describe the domains and utilities
3) a mix of 1 and 2 (limiting the depths of logical paths)
4) other

Examples would be:

1) 
```typescript
import {log, transform} from  'liferay-js-toolkit-core';

log.debug('hi');
transform.js.transformSource('var a', tranform.js.operation.wrapModule());
```

2) 
```typescript
import log from  'liferay-js-toolkit-core/log';
import {transformSource} from  'liferay-js-toolkit-core/transform/js';
import {wrapModule} from  'liferay-js-toolkit-core/transform/js/operation';

log.debug('hi');
transform.js.transformSource('var a', tranform.js.operation.wrapModule());
```

3) 
```typescript
import log from  'liferay-js-toolkit-core/log';
import transformJs from  'liferay-js-toolkit-core/transform/js';

log.debug('hi');
transformJs.transformSource('var a', transformJs.operation.wrapModule());
```

4)
:shrug:

**Comment by izaera** [comment]
Note that when I talk about some domains inside the package I mean `some`, not `several` or `hundreds`.

This package should not be a box where every utility is dumped, but it will be, for sure, a package with more than one independent "subpackages". The common thing between them is that they will all be used for the same problem (JS projects inside the Liferay domain).

But we need one package to share code for the generators, tools, utilities, whatever we make (like JS themes generator, JS themes build, JS portlets build, ....) and we want just one package, not one per independent domain to ease releases.

**Comment by wincent** [comment]
I personally like the idea that the "main" entry point be a manifest of the *entire* public API of the package. As soon as you open the door to reaching into a package and accessing specific paths:

- You no longer have a clear boundary between bits that are considered "private" and bits which are "public", unless you encode it in the path (eg. ok to import "pkg/something/foo" but not "pkg/private/bar" or "pkg/internal/baz"). I think encoding it in the path is too subtle which means that consumers may not understand it and implementers may forget the rules.
- As soon as you let people require by "deep" path, you lose the ability to ever move or restructure the package internally, because you've made your internals into externals.

Other reasons I like the "index as manifest of public API" approach:

- ES6 has great syntax for re-exporting stuff from other modules (eg. `export {blah} from './some/place'` etc).
- Modern tools can tree-shake so that the surface area of the index file doesn't matter.
- This approach provides natural feedback about package size and cohesiveness: that is, long before your index grows to be 2,000 lines long, it is already giving you feedback that you have gone too far down the path of turning it into a kitchen sink.
- Likewise, it's not just file-length that gives that kind of built-in feedback; it's naming too — because your named exports each have to have unique names, it forces you to have clear and distinct concepts with unique identifiers for each thing that you export.

[graphql-js](https://github.com/graphql/graphql-js/blob/master/src/index.js) is an example of a project that I used to work on that takes this approach about as far as I'd want to. At 446 lines, the index is starting to strain the limits of manageability, but you can see in that project a great example of how the internal structure of the project is very neat (look at the subfolders), and the index is literally just a manifest of it all.

**Comment by izaera** [comment]
I think I agree and `graphql-js` looks exactly like what I was thinking in 1. I'll go with that and see what happens.

:+1:

**Comment by jbalsas** [comment]
> graphql-js is an example of a project that I used to work on that takes this approach about as far as I'd want to. At 446 lines, the index is starting to strain the limits of manageability, but you can see in that project a great example of how the internal structure of the project is very neat (look at the subfolders), and the index is literally just a manifest of it all.

![beautiful](https://user-images.githubusercontent.com/905006/81315412-8fc28d00-908a-11ea-9684-2658f5d79679.gif)

**Comment by izaera** [comment]
Even though the API is not yet finished, I consider we can close this as done because the following actions will be taken in their corresponding issues.
