### ISSUE TITLE
Implement automatic imports

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-js-toolkit#532]
This will implement a mechanism to be able to use imports with zero configuration.

This issue is an iteration over #520, which contains the main discussion on how to implement this one.

**Comment by izaera** [comment]
TL;DR of #520:

We want to have projects like this:

```
my-project
	packages
		react-provider
		react-portlet
```

where `react-portlet` consumes `react` from `react-provider` using the `imports` mechanism without any need to configure anything than `package.json` files.

For that, we will have:

`react-portlet/package.json`
```json
{
	"name": "react-portlet",
	"version": "1.0.0",
	"peerDependencies": {
		"react": "*",
		"react-dom": "*"
	}
	"dependencies": {
		"react-provider": "^1.0.0"
	}
}
```

`react-provider/package.json`
```json
{
	"name": "react-provider",
	"version": "1.0.0",
	"dependencies": {
		"react": "^16.8.6",
		"react-dom": "^16.8.6"
	}
}
```

**Comment by jbalsas** [comment]
What's the point in having `react-portlet/package.json` actually depend on `react-provider`?

This feels more of a bundler configuration thing than a package concern. This feels upside down to me. If I'm building an App, what I see is:

```
react     |
react-dom | -> MyApp
leftpad   |
```

Nowhere there is `react-provider`. I have real dependencies on those packages and if I took my code elsewhere, those dependencies are the ones that matter. 

Now, in our context, someone is going to just swoop in and say:

```
alias: {
    react: 'react-provider/react'
    react-dom: 'react-provider/react-dom'
}
```

So, rather than putting the burden on the unsuspected developer app, I'd prefer to sweep it under the infrastructure carpet...

**Comment by izaera** [comment]
Some quick thoughts on your comment:

1) So, what you are basically proposing is not to do something automatic and continue like we were doing it in bundler 2 (configuring imports in a file specific to our toolkit)?

2) The assumption that react-provider is not a dependency may or may not be true. On the one hand it may not be if you only want to pull react from it, but you may also want to import local modules too. 

In any case, the necessity to import `react-provider` or not depends on how you want to model imports (make them explicit during build time vs making them more a deployment thing under the hood). I'm not sure which is best but I tend to think that if you will end up using the same react copy for several projects, you should setup your projects accordingly, and make it explicit that you want to pull the same `react` for all of them from `react-provider`, instead of struggling with linters and/or scripts to align all the package.json files of those projects...

**Comment by wincent** [comment]
This discussion may be going around in circles because I've lost track of what's been said in all the different threads, so please forgive me if my comments don't drive us closer to a conclusion, but there's one aspect I'd like to remark on.

The thing that I like about this "boilerplate":

```json
{
	"name": "react-portlet",
	"version": "1.0.0",
	"peerDependencies": {
		"react": "*",
		"react-dom": "*"
	},
	"dependencies": {
		"react-provider": "*"
	}
}
```

is that it is super explicit. Without knowing *anything* about how the bundler works, this tells me:

- My project *needs* "react"/"react-dom" *but* expects them to be available from a peer — without reading any further, I already know the intent is to leverage shared copies.
- My project depends on a "react-provider" package... 🤔 — I can pretty reasonably hypothesize that that's where the shared React is going to come from.

Compare that to the current system:

- Packages declare an explicit dependency on "react".
- An *optional, invisible* configuration file (`.npmbundlerrc`) *may* contain mapping telling bundler to reroute that dependency via a shared location. Anecdotally, using this mapping is so difficult that I have seen @izaera have to explain it *repeatedly* to members of the *Frontend Infrastructure Team*. [The configuration reference is very good](https://github.com/liferay/liferay-js-toolkit/wiki/.npmbundlerrc-file-reference), but at over 600 lines of dense information, it can be overwhelming.
- Even-more-invisible configuration ([hidden inside a preset file in another package](https://github.com/liferay/liferay-npm-tools/blob/897e19e955d8c8e671a79603ea6978f9cb863a41/packages/liferay-npm-bundler-preset-liferay-dev/config.json#L85-L94)) may take of this configuration for us magically.
- The mysterious hidden preset takes effect by default due to [another config, hidden inside yet another NPM package](https://github.com/liferay/liferay-npm-tools/blob/897e19e955d8c8e671a79603ea6978f9cb863a41/packages/liferay-npm-scripts/src/config/npm-bundler.json#L2).

To be honest, it is hard to qualify the system as anything other than diabolical... The dumb/explicit boilerplate looks pretty darn good in comparison. And as I get older and my mental faculties fade, the dumber option is going to look better and better... 😂

**Comment by jbalsas** [comment]
Hey @wincent, @izaera, just a couple of thoughts on 

```javascript
{
	"name": "react-portlet",
	"version": "1.0.0",
	"peerDependencies": {
		"react": "*",
		"react-dom": "*"
	},
	"dependencies": {
		"react-provider": "*"
	}
}
``` 

> Without knowing anything about how the bundler works

To me, this is exactly the opposite. With this, **developers (internal and external) are  forced to know** that something else is going on and that they have to explicitly use a rather exotic project configuration.

By doing this, we're surrendering the current infrastructure leverage we have. That is, we can introduce low-level, performance improvements without changing the underlying nature of the projects and without having to force this knowledge down.

There's 2 main things that concern me:
- We can't introduce improvements (like extracting a "peerDependency") without modifying all consumers
- It will also be harder for us to optimize "adapted" apps in the future since we will need them to conform to our "explicit" configuration mindset.

In line of this, I'd suggest we track [Merge Proposal: Module federation and code sharing between bundles. Many builds act as one](https://github.com/webpack/webpack/issues/10352) closely and even defer defining and implementing this until that's all clear.

**Comment by izaera** [comment]
I agree with @wincent. Also, I would like to add:

1) This is only a feature to make provider/consumer pattern more friendly (especially in the context of liferay-portal). It's not that everybody must do it this way.
2) No matter how we implement this, people will still have the ability to write imports config as they did in v2, providing the maximum flexibility.
3) The usual way to write consumer/provider applications (from what we've seen until now) is to have a monorepo with all the projects or several coordinated repos managed by the same team. It's not that some third party writes a provider and others use it.

Thinking of a real react application divided into several projects, the way to go seems to be: 

1) Specifying react version in the app project and 
2) Setting react as a peerDependency in the widget projects (see [material-ui](https://github.com/mui-org/material-ui/blob/master/packages/material-ui-icons/package.json#L40) or [react-bootstrap](https://github.com/react-bootstrap/react-bootstrap/blob/master/package.json#L61) as an example)

Indeed, if you specify react as a real dependency in the widget projects you may end up with more than one react version in the final dep tree which may cause problems. You could argue that deduplication should take care of that, but peerDependency seems more correct to me, since if you are writing a widgets library you expect someone to put react in place for you, not to pull if yourself, given that it is the framework of the whole project.

**Comment by jbalsas** [comment]
> [...] if you are writing a widget library you expect someone to put react in place for you [...]

The fact is that Blogs, Journal, AppBuilder... are **Applications** and not widget libraries. I assume that's exactly the developer that you'd expect to provide `react`. Otherwise, you might need to expand your concept of "widget library"...

**Comment by izaera** [comment]
> The fact is that Blogs, Journal, AppBuilder... are Applications and not widget libraries.

Nope, from the point of view of how we structure bundler projects, blogs, journal, etc. are widget libraries and the app is the portal. 

That's why you have one single react provider in portal and a single yarn monorepo, because the whole portal is treated as a single runtime unit by us.

**Comment by izaera** [comment]
Of course, there's no need to do it that way. You could also think that blogs, journal, etc. are apps and you provide a mechanism to collapse all in a single runtime unit but that makes things much more complex so, if we want to follow that model, we should be sure that it is worth it.

**Comment by jbalsas** [comment]
> Nope, from the point of view of how we structure bundler projects, blogs, journal, etc. are widget libraries and the app is the portal.

That's the thing... this is **OUR point of view** and not the point of view of those writing those apps.

**Comment by izaera** [comment]
@jbalsas Who are those? Customers or portal teams?

**Comment by jbalsas** [comment]
> Customers or portal teams?

Product Teams in Portals.

> And why do you know it's not their view?

You can ask them... based on my conversations, they consider their apps as their product. The aggregate... not so much. We're struggling in many cases to make them understand why can't just they add a new flashy dependency, so this is a clear indicator each team cares about their project. I'm not making any assessments as of what this means, just what I think it is.

All I'm trying to say is... please, before making a decision consider:
- What do the Product Team developers expect?
- What do we expect the Product Team developers to do and how are we going to teach them?
- Which path leaves us room for improvement in the future with the minimal impact on existing codebase?
- What are similar approaches being explored in the wild that we'd like to piggyback rather than reinvent? -> [Merge Proposal: Module federation and code sharing between bundles. Many builds act as one](https://github.com/webpack/webpack/issues/10352)
- What do External developers expect?
- What do we expect External developers to do and how are we going to teach them?

**Comment by wincent** [comment]
> * What are **similar approaches** being explored in the wild that we'd like to piggyback rather than reinvent? -> [Merge Proposal: Module federation and code sharing between bundles. Many builds act as one](https://github.com/webpack/webpack/issues/10352)

We should definitely take into account what's happening in the broader "webpack/Parcel/Rollup" etc ecosystem but I would urge extreme caution before taking the particular "module federation" approach from that issue as being a sure indication of what is eventually going to land in webpack. A lot of the details could change between now and when it eventually lands. At the moment, I view it as [hot-off-the-press marketing hype](https://indepth.dev/webpack-5-module-federation-a-game-changer-in-javascript-architecture/), and it could be very costly for us to chase it if it is a moving target.

**Comment by izaera** [comment]
Well, this feature was trying to accomplish points 6 and 7 in the [bundler 3 proposal doc](https://docs.google.com/document/d/1XanxNu5VfpJc7P4papplZ8dJorwvQCwkZDfmVhEZK98/edit?usp=sharing):

> [6] In addition, if we provided the bundler with some sort of definition of what to expect to be exported in a certain portal setup (something similar to Eclipse’s target platforms) we would be able to make validations, suggest configurations or even attain zeroconf. We are doing this now with the liferay-npm-bundler-preset-dev which injects known imports (like react provided by frontend-js-react-web) but we should promote it to something more explicit and easier to manage.

> [7] If we decide to implement this target platforms feature, we would need to publish standard target platforms for the public consumption (for example: Liferay CE 7.2, Liferay DXP 7.2, and so on) and we would also need a tool for development that connects to a running portal and generates a target platform file on the fly. This would become handy when using master’s portal.

One way to do it is via `package.json`, but we can also think of other ways to implement it. In the first place (the document) we suggested some external file to describe what the portal is exporting that would be consumed by the bundler (as opposed to the npm tools generating a preset under the hood). Or we can even leave it as it is now.

The problem I see with the current approach is that nobody (even me) is capable of reasoning with ease about the imports configuration because of what @wincent said. My experience is that having so much hidden under the hood makes people forget about it and, in the cases when we need to diagnose and change anything it takes quite a lot of effort to do it.
 
But, to be honest, after #520 and this new conversation I declare myself in a deadlock so I will leave this to be implemented later. I will try to enumerate all the possibilities I can think of in a document. Maybe comparing them at a glance will make it easier to decide...

**Comment by jbalsas** [comment]
@wincent 
> [...] I would urge extreme caution before taking the particular "module federation" approach from that issue as being a sure indication [...]

Agree 100%

@izaera 

> [...] nobody (even me) is capable of reasoning with ease about the imports configuration [...]

I doubt this will actually change... it's easy to reason with a 0-dep example like the one described, but real cases will become more and more nuanced. For one, how will we reason with [recharts deps and peerDeps](https://github.com/recharts/recharts/blob/master/package.json#L54-L70)? 

I think this is a complex problem. No matter what we do, it will be hard to understand. My question is... who do we need to understand the problem and what level of understanding? I'd expect some members of infra to be able to grasp the concept and internals to a high degree and Portal Developers to just have an idea of what's going on... it's okay if if we want Portal Developers to know more about it, I'm just asking to think about why and weigh in the pros and cons of this decision.

I think `automatic imports` is actually independent of how we model imports/exports, so maybe this discussion is going in the wrong direction. We should first figure out how to model this problem and then put it to the test for the features we want to build on top.

**Comment by izaera** [comment]
> I think automatic imports is actually independent of how we model imports/exports, so maybe this discussion is going in the wrong direction. We should first figure out how to model this problem and then put it to the test for the features we want to build on top.

Let's go with #550 first, then. And then we revisit this.

**Comment by jbalsas** [comment]
Doing some autumn cleaning as we move this project to https://github.com/liferay/liferay-frontend-projects#js-toolkit

We'll be curating these and creating new ones mostly from scratch to have a better sense of where we want to go.
