### ISSUE TITLE
Decide final configuration API for exports

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-js-toolkit#550]
Currently we have `imports` and `exports`. 

But webpack has `entry`, very similar to  `exports`.

What shall we use?

**Comment by izaera** [comment]
We still use `imports` because it was called like that in Bundler 2, but as we are developing a new version, we can change it.

However, we should not deviate from Bundler 2 more than necessary because it will make migration more difficult. 

Though in the case of `imports` you need to migrate the config anyway by moving it to a different section, so the developer could as well rename it in the same step.

**Comment by jbalsas** [comment]
So, in general terms, I'd like to reuse existing, well-defined concepts when possible instead of having to cook our own.

### Exports

This seems analog to [webpack Entry Points](https://webpack.js.org/concepts/entry-points). It supports:
- [Single Entry (Shorthand) Syntax](https://webpack.js.org/concepts/entry-points/#single-entry-shorthand-syntax): `entry: string | [string]`
- [Object Syntax](https://webpack.js.org/concepts/entry-points/#object-syntax): `entry: { <entryChunkName> string | [string] }`

### Imports

This might be similar to [webpack Module Resolution](https://webpack.js.org/concepts/module-resolution/) which uses the [Resolve API](https://webpack.js.org/configuration/resolve/#resolve). This is also somewhat connected with [Yarn Resolutions](https://classic.yarnpkg.com/en/docs/package-json#toc-resolutions) in the sense that regardless what a `package.json` says, you're giving an app a different dependency. Bits of this API that would be helpful:

#### [`resolve.alias`](https://webpack.js.org/configuration/resolve/#resolvealias)

```javascript
  resolve: {
    alias: {
      Utilities: path.resolve(__dirname, 'src/utilities/'),
      Templates: path.resolve(__dirname, 'src/templates/')
    }
  }
```

#### [`resolve.mainFields](https://webpack.js.org/configuration/resolve/#resolvemainfields)

```javascript
  resolve: {
    mainFields: ['browser', 'module', 'main']
  }
```


#### [`resolve.mainFiles](https://webpack.js.org/configuration/resolve/#resolvemainfiles)

```javascript
  resolve: {
    mainFiles: ['index']
  }
```

We shouldn't need to implement the whole `resolve` API... and I am afraid of running straight into the [Uncanney Valley](https://en.wikipedia.org/wiki/Uncanny_valley), so I wouldn't mind a second opinion on this...

**Comment by wincent** [comment]
re: Uncanny Valley — the bundler was born there, started a family, and has a mortgage there. (This was always going to happen, as soon as we decided to make our own "like-webpack-except" bundler.)

I think as a rule of thumb, you already hit on the two principles that are important to guide us:

- If we can do something by following a "standard"/"expected" API pattern, then we should.
- Insofar as is possible, defer implementing features within that API until we have a proven need for them.

**Comment by izaera** [comment]
Imports are not similar to `resolve` because:

1) resolve ends up being a synchronous require; imports end up being asynchronous requires
2) resolve simply decides where to find a file to be embedded in the webpack bundle while imports need to tweak the resulting package.json and rewrite the require

We can make imports configuration resemble webpack's API but given the differences I'm not sure if it is such a good idea, because people will have the same expectations but it will behave "a bit different". And this mismatch between what people expects and what the bundler can really do given its constraints (portlet platform) has always been a source of problems.

However, we ran that experiment with loaders, which are not exactly the same as webpack's and it seems that it has gone better than creating our brand new concept.

So, we may use something like:

```json
{
	"resolve": {
		"alias": {
			"react": "react-provider@^16.8.6/react"
		}
	}
}
```

instead of:

```json
{
	"imports": {
		"react-provider": {
			"react": "^16.8.6"
		}
	}
}
```

However, keep in mind that another constraint when designing v3 was to resemble v2 as much as possible to ease migration which goes against "following a "standard"/"expected" API pattern" when we are trying to switch an existing feature that hasn't followed the standard to a new configuration following the standard.

**Comment by jbalsas** [comment]
Doing some autumn cleaning as we move this project to https://github.com/liferay/liferay-frontend-projects#js-toolkit

We'll be curating these and creating new ones mostly from scratch to have a better sense of where we want to go.
