### ISSUE TITLE
Adapted Portlets Not Processing Changes?

### ISSUE THREAD

**Issue by mfreeman-xtivia** [liferay/liferay-js-toolkit#557]
So i am seeing an issue with "adapted" portlets, i.e portlets where i created the portlet initially using a CLI tool. I am seeing this behavior both with Angular portlets and with React portlets.

As an example i create a new React portlet, with package.json version=0.1.0. I then run 'yo liferay-js:adapt' on the portlet and deploy it, and install it on a page. All is well. Now if i simply make some changes in App.js and do a re-deploy of the JAR created by 'npm run build:liferay' the changes are not reflected in the portlet installed on the page.

Now if i uninstall the portlet from the page, and then re-install it on the page, the changes are reflected.

I am at a loss to understand what's going on here and under the covers with the JS Portlet Extender and the Combo Loader. What happens for example when the second copy of the portlet 'shows up' and says "i am carrying version 0.1.0 of package my-portlet'? Does the module loader reject the second copy?

**Comment by jtumano** [comment]
Hi! Try to delete build and dist directories before executing deploy.

**Comment by mfreeman-xtivia** [comment]
Why would that be necessary, i.e. what would be hanging around there that would need to be cleaned up?

**Comment by jtumano** [comment]
I don't know, maybe maintainers can answer, but we had same issue in our project before and found that bundler is quite lazy and doesn't delete nor overwrite previous build so as a workaround we are using `"prebuild": "rm -rf ./build"`  script in package.json where we are cleaning generated directories

**Comment by izaera** [comment]
:thinking: The bundler is quite bad at detecting dependency changes. This is due to historical reasons because the first versions of the bundler used the same files as input and output, so there's no way to know if something needs to be rebuilt :-(. This will hopefully be fixed in [bundler 3](https://github.com/liferay/liferay-js-toolkit/milestone/52).

So, what the bundler does is:

1) for project code: always build it
2) for node_modules dependencies: once they are written to the build directory, never rebuild them again

Number 2 almost always work because node_modules dependencies are immutable. But if, for example, you change the .npmbundlerrc file, your built node_modules dependencies may become stale.

Now, said that, I don't see why adaptations would need a rebuild because there are no node_modules dependencies involved in adaptations. But I may be wrong, I'm just talking off the top of my head.

Another source of problems could be the portal itself, because it usually caches things aggressively, so maybe you need to configure your portal.properties with development values... 

In fact, I strongly recommend doing so while developing so that errors are more easily diagnosed and to make sure nothing is cached, too.

**Comment by mfreeman-xtivia** [comment]
The workaround suggested by @jtumano of deleting the build.liferay and build directories in a pre-build step seems to be working for us as well so closing this issue
