### ISSUE TITLE
Bundler v3 status

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-js-toolkit#561]
Seeing as the v3 work has been on hold for a bit while we've been working on [the themes toolkit](https://github.com/liferay/liferay-js-themes-toolkit), I wanted to create this ticket so we have a space to just take stock of where the v3 project is and what we plan to do [in the milestone](https://github.com/liferay/liferay-js-toolkit/milestones/IFI-851%20%7C%20Bundler%203.x).

Basically, because we had a lot of open threads going on there, and I've lost most of the mental context, and with @jbalsas out, if he asks me for the status of the epic/milestone, and if there are any blockers, and if the way forward is clear, I don't really know the answer.

Don't need to go into crazy detail answering this, @izaera, but it would be good to have a snapshot of your thoughts when you get a chance to get your head back into the space of this project again.

**Comment by izaera** [comment]
We first wrote [this document](https://docs.google.com/document/d/1XanxNu5VfpJc7P4papplZ8dJorwvQCwkZDfmVhEZK98/edit?usp=sharing) which listed the basic improvements we wanted bundler 3 to have:

1.Define a good protocol to communicate bundler with loaders (?)
2.Get rid of old plugin types (pre/post and bundler)
3.Provide some way to perform package namespacing with loaders (?)
4.Serve module definitions to client in the resolve modules call
5.Explicit exports
6.Target platforms (?)
7.Tool to create target platform definitions from running portal instances (?)
8.Incremental build
9.Live reload
10.Multi-target build
11.Adaptive module serving
12.Transpilation of node_modules files
13.Linter
14.Linter IDE integration
15.Generalize common JS/Themes code in a shared npm package
16.Change release policy of JS Toolkit

Now, of these, we must note:

1) Won't be done as we won't have loaders in bundler 3.
2) It's done.
3) Same as 1 (I believe).
4) Not really needed for bundler 3 (it should be done in loader and portal).
5) Already working though we need to rework the specs (#508). There's a [document](https://docs.google.com/document/d/1DPb8gySLSToOjZsgn3ZhYtOAaSXqQbTsaOK8ycQ93ao/edit?usp=sharing) explaining how it works.
6+7) This is more or less what it's being discussed in #532. Given how unclear it is I think this shouldn't be in the first bundler 3 release. 
8) Not sure if this will be very much needed for bundler 3 initial release given how fast it is now.
9+10) These can be delayed for further iterations to be done after bundler 3 initial release.
11) It's more a thing to be implemented in portal and probably should be done on top of 4.
12) This is done as webpack is taking care of node_modules now.
13+14) I guess this can be done after first release, once we have clear what we want to lint and what are the most frequent errors.
15) We definitely want to have this (#526) before the first release otherwise there's risk of future breaking changes and also Themes Toolkit is depending on this to structure it's code a bit better 
16) We haven't released production versions, but we are already releasing pre-releases per module, so this is almost done.

Up to date, we have achieved:

1) bundling everything with webpack (thus making loaders and plugin unnecessary)
2) making explicit exports works 
3) make imports work again (with explicit exports)
4) we are using a bundler 3 pre-release in portal's build and it's integrating well with bundler 2 artifacts

And the following steps I have in mind (to get to bundler 3 initial release) are:

1) Make adaptations work (#521, #522 and #523)
2) Refactor the shared module (and probably the Themes Toolkit to make use of it) (#526)
3) Migrate generators (#527)
4) Forward-port issues fixed in bundler 2 (#530)
5) Add release script (#534) and enhance watch (#549)
6) Check configuration schema a la webpack (#536). Though not strictly necessary I think it would help a lot with migrations from bundler 2 to 3.
7) And, of course, we need to decide the final configuration schema before release (#550 and maybe some other configuration values that may appear during the development).
8) Document everything to a level similar to that of the current wiki.

I think that's pretty much all.

**Comment by izaera** [comment]
I'm closing this as it is now obsolete and I'm doing a new progress check.
