### ISSUE TITLE
Angular CLI Adapter -- What Does adapt_rt.js do?

### ISSUE THREAD

**Issue by mfreeman-xtivia** [liferay/liferay-js-toolkit#574]
Can someone tell the reason for this function that is in the generated output files?

I am guessing that it has something to do with relative image URL transformation so that they work inside Liferay?

If so how is it used in the code?

**Comment by izaera** [comment]
Your guess was right :-). That file is JS code to be able to retrieve static resources from Liferay Portal. Adapted applications usually assume that everything is under `/`, but that's not the case in Liferay, because you are deploying adapted applications as portlet, so they live in `/o/portlet-name/...`.

Also, Liferay Portal has the concept of CDN, webapp context, etc... and we try to account for them when they are configured.

The `adapt_rt.js` code is not intended to be used by you, it's just a helper that the bundler assumes will be available to rely on it to generate such URLs.

If you want to do the same I would advise to copy&paste the code from `adapt_rt` to your application so that you can manage it and maintain it. Otherwise we can remove/change `adapt_rt` in a future release and break your code.

**Comment by izaera** [comment]
One final note: even though we try to use `adapt_rt` as much as we can in the adapted code, there's the possibility that some of the URLs escape to our transformation (this is because it's impossible to detect all of them as we would need to truly **understand** the code).

Also, we cannot run URLs in .css files through `adapt_rt` because we cannot execute JS code in CSSs. In those cases we simply rewrite the URL to point to `/o/something...` but if you configure, for instance, a CDN, it won't be honored unless you tweak your .css file accordingly.
