### ISSUE TITLE
Can I upgrade a portlet to Angular 9?

### ISSUE THREAD

**Issue by Lcpp0** [liferay/liferay-js-toolkit#628]

**Comment by izaera** [comment]
I would say, just try it and file a bug if something bad happens. 

The last tested version is always the one the generator configures. That doesn't mean newer versions don't work, but simply that we haven't tested them yet. Also, we aim at supporting the latest versions of the supported frameworks, though it is almost impossible given how fast they release. So we do it reactively instead of proactively.
