### ISSUE TITLE
Differences between 2.x bundler and 3.x bundler?

### ISSUE THREAD

**Issue by aggie2016** [liferay/liferay-js-toolkit#639]
Just at a high level, what improvements should we expect to see from the new 3.x bundler?

**Comment by aggie2016** [comment]
Our current project deploys to portal nicely, however due to our dependencies in `package.json`, the final `.jar` file is in excess of 250MB 😮! Is this typical for a `package.json` with 80 dependencies (most are typings for typescript)? 

The typical react-scripts production build using Webpack is <5MB. Even if we had 10 of these portlets on the same page sharing dependencies, that's still only 25% of the total file size of our JAR file built with `liferay-npm-bundler`. Since then, we've had a quite a bit of success placing the smaller production build into a custom portlet and deploying to Liferay as-is. 

I'm in no way fully aware of all the technical challenges that were solved during building this bundler but would an approach that uses the minified/chunked output from Webpack directly have more benefits? 
- Reuse of existing project structure generated by create-react-app (with some additional metadata needed for Liferay).
- No need to move image assets into a separate folder instead of directly importing them the standard way recommended by the React documentation.
- No need to scan and copy whole folders from `node_modules/`.
- No need to add css styling using `@import` tags in a single `styles.css` file. These can also just be imported directly and loaded by Webpack plugins at build time.
- Near similar build time to that of the existing `react-scripts build`. Right now our build time is on the order of 20 minutes (for the first build). Subsequent builds are somewhere between a minute to 2 minutes.

**Comment by izaera** [comment]
> Just at a high level, what improvements should we expect to see from the new 3.x bundler?

Basically everything is done is by webpack except for the imports, which are still handled by the bundler. Also, each webpack entry is exported as an AMD module so that it remains interoperable with previous (bundler 2, 1 and older config-generator) code.

> Our current project deploys to portal nicely, however due to our dependencies in package.json, the final .jar file is in excess of 250MB open_mouth! Is this typical for a package.json with 80 dependencies (most are typings for typescript)?

This happens because the bundler cannot know in advance which modules will be used and which don't so it has to pack everything just in case it is used during runtime. Webpack, on the other hand, only includes things you use and everything else is removed.

If the bundler did the same webpack does, things would break when someone from another projects tries to use any package you may be exporting in yours.

So, to avoid this problem, you may use the [exclude option](https://github.com/liferay/liferay-js-toolkit/wiki/.npmbundlerrc-file-reference#exclude) to remove any files you don't want in the final JAR. This is for bundler 2.

In bundler 3 we are using the opposite approach: instead of telling what to exclude, you define which modules are exported through the AMD loader and the rest remains private to your project. This way, the bundler can do a much more efficient optimization because it can assume that everything not in the exports can be ignored if it is not necessary for your project (as webpack does).
